/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class compiler_codegen_CppASTBridge */

#ifndef _Included_compiler_codegen_CppASTBridge
#define _Included_compiler_codegen_CppASTBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     compiler_codegen_CppASTBridge
 * Method:    getASTPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_compiler_codegen_CppASTBridge_getASTPointer
  (JNIEnv *, jobject);

/*
 * Class:     compiler_codegen_CppASTBridge
 * Method:    generateWasmFromAST
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_compiler_codegen_CppASTBridge_generateWasmFromAST
  (JNIEnv *, jobject, jlong);

/*
 * Class:     compiler_codegen_CppASTBridge
 * Method:    getASTAsJson
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_compiler_codegen_CppASTBridge_getASTAsJson
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
