package compiler.lexer;

public enum TokenType {
    VAR, TYPE, IS, INTEGER, REAL, BOOLEAN, ARRAY, RECORD, END,
    WHILE, LOOP, FOR, IN, REVERSE, IF, THEN, ELSE, PRINT, ROUTINE,
    TRUE, FALSE, AND, OR, XOR, NOT,
    RETURN,
    IDENTIFIER, INTEGER_LITERAL, REAL_LITERAL, STRING_LITERAL,
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL, NOT_EQUAL,
    ASSIGN, RANGE,
    COLON, SEMICOLON, COMMA, DOT, LPAREN, RPAREN, LBRACKET, RBRACKET, ARROW,
    EOF
}
